# ¡Bienvenido a Jekyll!
#
# Este archivo de configuración está destinado a configuraciones que afectan a todo tu blog, valores
# que se espera que configures una vez y rara vez edites después de eso. Si te encuentras
# editando este archivo con mucha frecuencia, considera usar los archivos de datos de Jekyll
# para los datos que necesita actualizar con frecuencia.
#
# Por razones técnicas, este archivo * NO * se recarga automáticamente cuando usas
# 'bundle exec jekyll serve'. Si cambias este archivo, reinicia el proceso del servidor.

# Configuración del sitio
# Esto se utiliza para personalizar tu nuevo sitio. Si miras en los archivos HTML,
# Verás que se accede a ellos a través de {{site.title}}, {{site.email}}, etc.
# Puedes crear cualquier variable personalizada que desees y será accesible
# en las plantillas a través de {{site.myvariable}}.

title: Tower Builder

# Imagen del logo
image: tb-logo.png

#Descripción de tu sitio
description: >-
  TowerBuilder is a system to generate websites with data visualizations that mix open contracting and beneficial ownership data, all without requiring programming knowledge.


# URL del archivo de contratos o del endpoint de tu API
contracts_url: "/assets/data/contracts.json"

# URL del archivo de beneficial ownership o del endpoint de tu API
bods_url: ""

graph:
  # EL nombre de tu gráfico
  - title: "Nombre del gráfico"
  # los tamaños minimos y maximos de los nodos (en pixeles, aproximado)
  - sizes:
    - min: 10
    - max: 300
  # colores de nodos y connectores
  - colours:
      - nodes:
          - default: '#1ee6d3'
          - contract: '#1ee6d3'
          - contractTypes: '#3abdc3'
          - contractByType: '#438a9c'
          - organization: '#3c5a6f'
          - shareholderPerson: '#EB639A'
      - links:
          - default: '#706F74'
          - contractsTypes: '#706F74'
          - toCenter: '#706F74'
          - toContractType: '#706F74'
          - toOrganization: '#706F74'
  - descriptionLink: "Ir al perfil"
  
# Personaliza el título del botón del menú Más información
menu_button_title: Más información

# Personaliza los títulos y placeholders de los inputs
# en el Buscador de contratos
contracts_title: Contratos por empresas
search_title: Búsqueda
search_placeholder: Introduce palabra clave a buscar
amount_title: Monto total (en pesos mexicanos)
amount_from_placeholder: Desde $
amount_to_placeholder: hasta $
type_contract_title: Tipo de contratación
type_contract_title_tooltip: La ley obliga a la Unidad Compradora a definir el tipo de contratación, ya que varían las normas en cada caso.
type_contract_all_option: Todo
type_procedure_title: Tipo de procedimiento
type_procedure_title_tooltip: La licitación pública es según la ley mexicana el procedimiento adecuado para contratar obra publica. Excepcionalmente también se pueden realizar otro tipo de procedimientos como adjudicación directa, convenio e invitación a cuando menos tres proveedores.
type_procedure_all_option: Todo
date_range_title: Rango de fechas
date_range_from_placeholder: Desde
date_range_to_placeholder: hasta
date_range_title_tooltip: Encuentra los contratos activos entre dos fechas.
filter_footnote_title: Los filtros aplican sobre los contratos que tienen las empresas.
# Personaliza los títulos de la tabla
column_1: Empresas 
column_2: Cant. de contratos
column_3: Monto total

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Excluir del procesamiento.
# Los siguientes elementos no se procesarán de forma predeterminada. 
# Crea una lista personalizada para anular la configuración predeterminada.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - docs/

# Colecciones
collections_dir: collections
collections:
  first-slider:
    output: true
  visualization-slider:
    output: true

# Cambia a false para ocultar extractos en la página de publicaciones.
show_excerpts: true
future: true

# Configura el lenguaje de las fechas en las páginas de publicaciones (es/en).
date-language: "es"

# Configura el formato de las fechas en las páginas de publicaciones.
# Otros formatos: "%a, %b %d, %y" | "%Y" | "%b %d, %y" | "%Y-%m-%d %H:%M"
date-format: "%B %-d, %Y"